### ISSUE TITLE
泰区番剧解析playurl的result缺少必要字段

### ISSUE THREAD

**Issue by Hinghuai** [ipcjs/bilibili-helper#898]
问题描述
本人能力有限无法确定脚本问题还是华为云代码配置问题

华为云使用的代码：
@zzc10086写的 [251_FunctionGraph_BPplayurl-for-Thailand.php](https://github.com/zzc10086/grocery_store/blob/35ecdbd4811ed1917f110949026f84b5695bb23a/bili_proxy/251_FunctionGraph_BPplayurl-for-Thailand.php)

- 问题网址：
[https://www.bilibili.com/bangumi/play/ss36940/?spm_id_from=333.999.0.0](https://www.bilibili.com/bangumi/play/ss36940/?spm_id_from=333.999.0.0)

## 日志
脚本日志无法导出。。。（右下角土星图标没了。。。）
![微信截图_20211106122555](https://user-images.githubusercontent.com/63064333/140598016-191e51b0-5c18-48de-b003-ae0ac2eeb6e0.png)

## 其他
1. 浏览器版本：Edge 95.0.1020.40 (官方内部版本) (64 位)
2. 国家/地区：上海移动
3. 脚本为最新版：8.2.10
4. 实测代码跨域问题已解决，已绑定独立域名不存在访问次数限制

**Comment by Hinghuai** [comment]
原代码存在跨域问题
[zzc10086给出的解决方案](https://github.com/zzc10086/grocery_store/issues/11#issuecomment-962090243)
实测能解决跨域

**Comment by Hinghuai** [comment]
哔哩漫游能正常（？）调动解析

测试番剧  [只有我们能进入的隐藏地下城](https://www.bilibili.com/bangumi/play/ss36934/?spm_id_from=333.999.0.0)

奇怪的是哔哩漫游只能解析出480P并且评论区无法显示

估计应该就是脚本问题了 @ipcjs

**Comment by JasonKhew96** [comment]
> 哔哩漫游能正常（？）调动解析
> 
> 测试番剧 [只有我们能进入的隐藏地下城](https://www.bilibili.com/bangumi/play/ss36934/?spm_id_from=333.999.0.0)
> 
> 奇怪的是哔哩漫游只能解析出480P并且评论区无法显示
> 
> 估计应该就是脚本问题了 @ipcjs

1. 泰区大会员不通用主站大会员
2. 泰区番剧不登录只有 480p，登录后 720p
3. 泰区域名都换了好几个了，不知道最早那个还能用么...

```
*.global.bilibili.com
*.biliintl.com
*.bilibili.tv
```

**Comment by Hinghuai** [comment]
> > 哔哩漫游能正常（？）调动解析
> > 测试番剧 [只有我们能进入的隐藏地下城](https://www.bilibili.com/bangumi/play/ss36934/?spm_id_from=333.999.0.0)
> > 奇怪的是哔哩漫游只能解析出480P并且评论区无法显示
> > 估计应该就是脚本问题了 @ipcjs
> 
> 1. 泰区大会员不通用主站大会员
> 2. 泰区番剧不登录只有 480p，登录后 720p
> 3. 泰区域名都换了好几个了，不知道最早那个还能用么...
> 
> ```
> *.global.bilibili.com
> *.biliintl.com
> *.bilibili.tv
> ```

应该是我的表述问题很大。。。
我现在的问题是脚本没办法解析出播放链接并报错，而同样的解析服务器哔哩漫游能正常解析出
（480P什么的先扔开，能看最重要）

**Comment by JasonKhew96** [comment]
脚本没有问题的（能播放，但字幕 emm 似乎有点残废了），有问题的是 代理服务器代码
![image](https://user-images.githubusercontent.com/29531167/140604701-c82865fd-a86d-4816-ad36-1f03c632558b.png)
![image](https://user-images.githubusercontent.com/29531167/140604708-17cb161a-bb6f-43fe-ae47-be0693635978.png)

**Comment by zzc10086** [comment]
目前主要维护得php和阿里云的代码,腾讯云和华为云的代码由网友提供,目前处于未维护状态.预计为泰国版b站得api接口换了,需要重新提取替换到脚本中,我这边没有泰国的代理╮(╯▽╰)╭

**Comment by Hinghuai** [comment]
找了个代理在上面提到的 地下城 番剧用fiddler抓了下包
[bilith11-7.zip](https://github.com/ipcjs/bilibili-helper/files/7490996/bilith11-7.zip)

**Comment by AisukaYuki** [comment]
可以尝试用[BiliRoaming-PHP-Server](https://github.com/david082321/BiliRoaming-PHP-Server)搭建。会稍微麻烦一些。

**Comment by zzc10086** [comment]
建议抓取APP客户端的API,使用/intl/gateway/v2/ogv/playurl可以解析到播放地址,但是cdn层面可能存在限制,报403错误.
也可以在php上直接重构一个含有reult的json返回给浏览器.两个api请求的链接大概率都有限制,具体是针对什么的要自己试了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ipcjs/bilibili-helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月7日(星期天) 凌晨2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ipcjs/bilibili-helper] 泰区番剧解析playurl的result缺少必要字段 (Issue #898)





 
找了个代理在上面提到的 地下城 番剧用fiddler抓了下包
 bilith11-7.zip
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzc10086** [comment]
建议抓取APP客户端的API,使用/intl/gateway/v2/ogv/playurl可以解析到播放地址,但是报403错误.
也可以在php上直接重构一个含有reult的json返回给浏览器.两个api请求的链接大概率都有限制,具体是针对什么的限制要自己试了
![image](https://user-images.githubusercontent.com/50003754/140643152-9ebe156f-ca29-401e-9f12-e1e115f14d43.png)
![image](https://user-images.githubusercontent.com/50003754/140643310-50433e0c-bc81-44da-940e-a654fb93df7f.png)

**Comment by BraveSail** [comment]
@zzc10086 
403 是因为 akamai 锁区，漫游的解决方法是替换 upos ，但是 web 这种方式不可行，因为 header 不对（需要设定为 app 的 header），目前脚本的泰区解锁只有挂了东南亚梯子才有效，这问题只能等 @ipcjs 来重建 XHR 请求了。
